### ISSUE TITLE
Compiling solutions with Q# unit test does not work

### ISSUE THREAD

**Issue by vivanwin** [microsoft/iqsharp#139]
**Describe the bug**
When using a solution with native Q# `@test()` the solution does not compile. It throws an error saying that `Microsoft.Quantum.Xunit` is not available, I have tried to add this in the `BUILT_IN_PACKAGES` inside of the references file, however more dependencies issues pop up.

**To Reproduce**
1. Create a Q# project which uses `@test()` statements, inside of the Jupyter notebook folder. I created a sample [here](https://github.com/vivanwin/QunitTest).
2. Load the notebook.

**Expected behavior**
The solution should compile without any issue, and the test should be able to be used within other projects like the [QuantumKatas](https://github.com/microsoft/QuantumKatas).

**Screenshot**
![image](https://user-images.githubusercontent.com/25651976/81278272-bca87d00-9055-11ea-9b4e-f29b41b5aa6f.png)

**System information**
 - OS: Windows
 - Browser: Edge (chromium)
 - Version: 0.11.2004.2825

**Comment by rmshaffer** [comment]
One way to work around this is to run `%package Microsoft.Quantum.Xunit` (ignore the harmless error messages that are being fixed in #203) followed by `%workspace reload`. This should compile the code successfully and allow the Q# operations to be run from inside the Q# notebook. It does not fix the compilation errors that occur on initial load, however.

One way to fix this would be for IQ# to read the package references directly from the .csproj file and to load those packages prior to compiling the Q# code in the folder.

An alternative approach to fixing this would be to implement project references for IQ# (see #24), and then have the .ipynb notebook file in a different folder from the Q# project, such that the code will only be compiled once the project and its package references have been loaded.

**Comment by rmshaffer** [comment]
This should now work when using the `<IQSharpLoadAutomatically>true</IQSharpLoadAutomatically>` property in the .csproj to load the required package(s) at initialization time. See https://docs.microsoft.com/en-us/quantum/user-guide/host-programs?tabs=tabid-python#using-q-code-from-other-projects-or-packages-1 for more details.
