### ISSUE TITLE
IQ# version error during install

### ISSUE THREAD

**Issue by theRomanMercury** [microsoft/iqsharp#143]
Hello ,

I try to install the IQ# but I got this error

PS C:\Users\90507\Desktop\Q\QuantumKatas-master\Measurements> dotnet iqsharp install
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '2.1.1' was not found.

The following frameworks were found:
3.1.3 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=2.1.1&arch=x64&rid=win10-x64

Do I need to change framework version to 2.1.1 or is there any other solution ?

**Comment by rmshaffer** [comment]
Thanks for reporting this issue! Since you closed the issue, it looks like you may have found a solution already. In case you haven't: it looks like you have an old version of IQ# installed that depends on a previous .NET Core version. The latest version of IQ# requires .NET Core SDK 3.1, which from the message, it looks like you already have installed. So you should be able to install and run the latest version of IQ#:
```
dotnet tool uninstall -g Microsoft.Quantum.IQSharp
dotnet tool install -g Microsoft.Quantum.IQSharp
dotnet iqsharp install
```
