### ISSUE TITLE
IQ# kernel fails to start when "Application Data" folder is inaccessible

### ISSUE THREAD

**Issue by geduardo** [microsoft/iqsharp#149]
Originally opened by @n33r4j:

I recently updated my iqsharp(from 0.10 to 0.11) for jupyter notebooks (via Anaconda) and ever since, the Q# kernel stopped connecting when I open a new or existing Q# notebook(Python works fine). I have tried uninstalling and reinstalling jupyter notebook as well as iqsharp but nothing seems to have changed.
I think it may have something to do with "Access to the path 'C:\Users\neera\Application Data' is denied".

**Comment by rmshaffer** [comment]
Hi @n33r4j, thanks for reporting! It looks like you've also reported this issue on StackOverflow at https://stackoverflow.com/questions/62009102/jupyter-notebook-q-kernal-not-connecting/62027491.

In general, it looks like something went wrong during installation/upgrade that is preventing IQ# from starting up as a Jupyter kernel. What you could try is to completely uninstall and reinstall the iqsharp tool by doing the following:

```
dotnet tool uninstall -g Microsoft.Quantum.IQSharp
dotnet tool install -g Microsoft.Quantum.IQSharp
dotnet iqsharp install
```

If that doesn't work, to diagnose further, it would be very helpful if you could provide a little more information:

- When specifically are you seeing that "access denied" error message? Is this in the Jupyter console output, or is it the output of some command that you are running?
- If you could also include more of the context around the error message, it would be helpful. For example, provide the full terminal output rather than just the single line with the error message.

**Comment by n33r4j** [comment]
I have tried uninstalling once before but I'll try it again.

I'll try to describe what happens.

When I open an existing or new Q# notebook, 
1) Notebook - The kernel status is "Kernel starting, please wait..."

2) Jupyter terminal window message - "Access to the path 'C:\Users\neera\Application Data' is denied.

3)  Notebook - The kernel status turns to "Connecting to kernel" (in orange).

4)  Notebook - A pop up dialogue box with the message, "A connection to the notebook server could not be established. The notebook will continue trying to reconnect. Check your network connection or notebook server configuration".

5) Jupyter terminal window message -"Replacing stale connection: ....".

6)  Notebook - After a few seconds, no status message. The indicator circle on the top right (which is usually white ) turns grey and shows 'Kernel Connected' when you hover the mouse over it. Yet the kernel remains unresponsive.

Below is the entire terminal output after opening an existing Q# notebook.

`
[I 19:03:26.794 NotebookApp] JupyterLab extension loaded from C:\Users\neera\Anaconda3\lib\site-packages\jupyterlab
[I 19:03:26.794 NotebookApp] JupyterLab application directory is C:\Users\neera\Anaconda3\share\jupyter\lab
[I 19:03:26.822 NotebookApp] Serving notebooks from local directory: C:\Users\neera
[I 19:03:26.822 NotebookApp] The Jupyter Notebook is running at:
[I 19:03:26.823 NotebookApp] http://localhost:8888/?token=d828aeca084b9876a9bf502beb65bdd92cd88e3e342397a5
[I 19:03:26.823 NotebookApp]  or http://127.0.0.1:8888/?token=d828aeca084b9876a9bf502beb65bdd92cd88e3e342397a5
[I 19:03:26.823 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 19:03:26.932 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/neera/AppData/Roaming/jupyter/runtime/nbserver-3340-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=d828aeca084b9876a9bf502beb65bdd92cd88e3e342397a5
     or http://127.0.0.1:8888/?token=d828aeca084b9876a9bf502beb65bdd92cd88e3e342397a5
[I 19:03:40.844 NotebookApp] Kernel started: aec54c2b-905b-4f50-b746-4a2c9b5ab6d5
Access to the path 'C:\Users\neera\Application Data' is denied.
[W 19:04:01.875 NotebookApp] Replacing stale connection: aec54c2b-905b-4f50-b746-4a2c9b5ab6d5:85606d3279fc431d8ec6fbd854aceff4
[W 19:04:23.890 NotebookApp] Replacing stale connection: aec54c2b-905b-4f50-b746-4a2c9b5ab6d5:85606d3279fc431d8ec6fbd854aceff4
[W 19:04:40.914 NotebookApp] Timeout waiting for kernel_info reply from aec54c2b-905b-4f50-b746-4a2c9b5ab6d5
[I 19:04:40.925 NotebookApp] Starting buffering for aec54c2b-905b-4f50-b746-4a2c9b5ab6d5:85606d3279fc431d8ec6fbd854aceff4
[I 19:04:40.927 NotebookApp] Restoring connection for aec54c2b-905b-4f50-b746-4a2c9b5ab6d5:85606d3279fc431d8ec6fbd854aceff4
`

**Comment by rmshaffer** [comment]
Thank you for the additional information! Which path are you starting `jupyter notebook` from? Can you try starting `jupyter notebook` from a different path? For example:
```
cd C:\Users\neera\Documents
jupyter notebook
```

**Comment by n33r4j** [comment]
It works! Is there a way I can change the directory?

**Comment by rmshaffer** [comment]
You could start `jupyter notebook` from `C:\` and then you can access your whole file tree from within the browser.

I think what is happening is that IQ# tries to browse the contents of the current folder for `*.qs` files on startup. In your case there's a folder `Application Data` that's inaccessible for some reason (we have seen a couple other reports of this), and IQ# doesn't handle that exception and fails to startup. So this certainly looks like a bug that should be fixed in IQ# (thank you for filing this issue!). But, the workaround is to simply start `jupyter notebook` from a different folder.

**Comment by rmshaffer** [comment]
Great, thank you for confirming!

Leaving this issue open to track the underlying bug here, and updating the title accordingly.

**Comment by rmshaffer** [comment]
Also linking the two StackOverflow questions where this issue has been raised recently:
- https://stackoverflow.com/questions/60949333/how-to-fix-this-problem-with-q-installation-preparing-q-environment-acces/62047266
- https://stackoverflow.com/questions/62009102/jupyter-notebook-q-kernal-not-connecting/62027491
