### ISSUE TITLE
Sample code's output doesn't match the docs' said one

### ISSUE THREAD

**Issue by theerfan** [microsoft/iqsharp#234]
**Describe the bug**
Hi. I wasn't sure where to post this issue, but I guess this is the right repo.
Following [this part](https://docs.microsoft.com/en-us/quantum/quickstarts/install-python?tabs=tabid-dotnetcli) of the docs, after literally copy-and-pasting the codes in there and executing "python host.py", instead of getting an output of either Zero or One (as said in the docs), I get this:

> Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
Microsoft.Quantum.Standard, Version=0.12.0.0, Culture=neutral, PublicKeyToken=40866b40fd95c7f5
Microsoft.Quantum.QSharp.Core, Version=0.12.0.0, Culture=neutral, PublicKeyToken=40866b40fd95c7f5
Microsoft.Quantum.IQSharp.Jupyter, Version=0.12.0.0, Culture=neutral, PublicKeyToken=40866b40fd95c7f5
Microsoft.Quantum.IQSharp.AzureClient, Version=0.12.0.0, Culture=neutral, PublicKeyToken=40866b40fd95c7f5
Microsoft.Quantum.Simulators, Version=0.12.0.0, Culture=neutral, PublicKeyToken=40866b40fd95c7f5
Microsoft.Quantum.Runtime.Core, Version=0.12.0.0, Culture=neutral, PublicKeyToken=40866b40fd95c7f5
Microsoft.Quantum.Simulation.Common, Version=0.12.0.0, Culture=neutral, PublicKeyToken=40866b40fd95c7f5
Microsoft.Quantum.Simulation.QCTraceSimulatorRuntime, Version=0.12.0.0, Culture=neutral, PublicKeyToken=40866b40fd95c7f5

I'm pretty sure the IQ# installed on my system is functional as it has no problem executing the Jupyter Notebooks in the [QuantumKatas](https://github.com/microsoft/QuantumKatas) repo.
I tested this on two different systems but I got the same result in either case.

**System information**
 - OS: Windows 10 64-bit
 - Python: 3.8.3 64-bit
 - .NET Core SDK: 3.1.201

**Comment by rmshaffer** [comment]
Thanks for reporting this issue, @theerfan! I think there are two issues here.

First, all of the "Microsoft.Quantum.*" output lines: This extraneous output is indeed an issue in the most recent release. It has been fixed by #220, which will be part of the next QDK version release, likely in late August.

Second, the lack of the `Zero` or `One` output: You're right, there is a small error in that documentation. In order to see the output, you would need a `print()` statement in your Python script. e.g., the last statement should be wrapped with `print()` as follows:

```
print(SampleQuantumRandomNumberGenerator.simulate())
```

If you do that, you should see `Zero` or `One` printed at the end of the output. Does it work for you? If so, I'll make sure the documentation is updated.

**Comment by theerfan** [comment]
Yes, it works.
Thank you for the quick response. 😄
