### ISSUE TITLE
qsharp and python: gets 'preparing qsharp environment' messages from console

### ISSUE THREAD

**Issue by Samet732** [microsoft/iqsharp#251]
**Description**
I started tutorial of qsharp and i wrote my first qsharp and python (host) codes. But when i run qsharp codes in console, gets some messages in console.

**Bug**
When runs qsharp codes in console with python3, gets some interesting messages about iq# in console.

**Expected Behaviour**
I think expected behaviour is iq# shows only qsharp codes output.

**Screenshots**
![qsharp-environment-message](https://user-images.githubusercontent.com/48414337/89828486-c87a7280-db61-11ea-8745-5e56b1208f0a.png)

**System information**
 - OS: Elementary OS (based on Ubuntu 18 LTS)
 - Python version: Python 3.6.9
 - .NET version: 3.1.302
 - QSharp version (pip3 module): 0.12.2007.2031

**Comment by rmshaffer** [comment]
Thank you for reporting, @Samet732! You're right that this is a bug. This looks like it has also reported in issue https://github.com/microsoft/iqsharp/issues/234, and has been fixed by PR https://github.com/microsoft/iqsharp/pull/220. The next release of qsharp (will be later this month) will have this issue resolved. Closing this accordingly. Please follow up if you have any further questions!
