### ISSUE TITLE
No image produced for %trace magic

### ISSUE THREAD

**Issue by crazy4pi314** [microsoft/iqsharp#271]
**Describe the bug**
If an operation that generates a valid circuit image with the `%trace` command is wrapped with another operation, the output image is empty.

**To Reproduce**
1. Define the following operations in your Q# notebook: 
```
operation ApplyH () : Unit {
    using (q = Qubit()) {
        H(q);
        H(q);
    }
}

operation ApplyHWrapper() : Unit {
    return ApplyH();
}
```
2. Run the trace command for both of the operations defined above:
```
%trace ApplyH
```
and
```
%trace ApplyHWrapper
```
**Expected behavior**
I would expect the traced image output of `ApplyHWrapper` to be the same as `ApplyH`.

**Screenshots**
![image](https://user-images.githubusercontent.com/6486256/90299390-bd1d9480-de4a-11ea-8cbe-9c9804aa1481.png)

**System information**
-Windows 10, EdgeDev, IQSharp version in screenshot

**Comment by theRoughCode** [comment]
This looks like it's happening because `ApplyH` does not have any qubits in its arguments. Since the default render depth is `1`, we render `ApplyH()` when we call `ApplyHWrapper` which has no target qubits (or so it seems from its arguments) so nothing is rendered. 

The way to fix this is to propagate the target qubits from the nested operations up to their parents. There's ongoing work that improves how we think of depth which would also fix this issue. Will update here once the PR is up. :)

**Comment by theRoughCode** [comment]
Update: #280 is in the works which will fix this.
