### ISSUE TITLE
Q# notebook cells have poor formatting in JupyterLab, nteract, etc.

### ISSUE THREAD

**Issue by vadym-kl** [microsoft/iqsharp#34]
**Describe the bug**
IQ# notebooks do not work in JupyterLab, the next-generation web-based interface for Project Jupyter.

**To Reproduce**
Start JupyterLab on a local machine with `jupyter lab`, try to run any IQ# notebook.

**Expected behavior**
IQ# notebook works the same way as in Jupyter Notebooks run with `jupyter notebook`

**Additional context**
This is a known problem with a known fix, as mentioned to me by @cgranade in personal communication.

**Comment by apd47** [comment]
Is there any update on a timeline for a fix for this issue? Jupyter Hub's utility in a classroom/lab environment is fantastic, and being able to use it would open doors for Q# experimentation in multiple use cases at my institution. Since (at least in our deployment) its a server instance issue that would only need to be done once, would local MIME type changes on both packages be our best bet for now?

**Comment by rmshaffer** [comment]
Thanks for the inquiry, @apd47! To clarify, this particular issue is referring to some compatibility issues between IQ# and the [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/) client. [JupyterHub](https://jupyterhub.readthedocs.io/en/stable/), on the other hand, should be fully compatible with IQ# as far as I know, and published IQ# images can be run in JupyterHub hosted on MyBinder (for example, [QDK samples](https://mybinder.org/v2/gh/Microsoft/Quantum/%E2%AD%90binder) and [Quantum Katas](https://mybinder.org/v2/gh/Microsoft/QuantumKatas/master?filepath=index.ipynb)).

Are you seeing any specific compatibility issues?

**Comment by rmshaffer** [comment]
Linking to a related issue https://github.com/microsoft/jupyter-core/issues/35.
