### ISSUE TITLE
Job submission fails when I follow the "Submit jobs" tutorials

### ISSUE THREAD

**Issue by singular-value** [microsoft/iqsharp#416]
**Describe the bug**
I created an Azure Quantum Workspace and believe I correctly followed all instructions.
However, when I try to run either of the Sumbit Jobs tutorials ([Q# Jupyter Notebook](https://docs.microsoft.com/en-us/azure/quantum/how-to-submit-jobs-with-jupyter-notebooks) or [Python](https://docs.microsoft.com/en-us/azure/quantum/how-to-submit-jobs-with-python)), the last step of actually executing/submitting the job fails.

**To Reproduce**
Here is a screenshot from trying it with a Q# Jupyter Notebook. It looks like the authentication succeeds. But no luck for the execution/submission.
![image](https://user-images.githubusercontent.com/3976048/109430708-56b42a00-79c8-11eb-98bd-f35058788628.png)

Similar story for Python, which also gives me `{'error_code': 1010, 'error_name': 'JobSubmissionFailed', 'error_description': 'Failed to submit the job to the Azure Quantum workspace.'}`.

Also FYI, the compilation itself succeeds, because I can do `%simulate GenerateRandomBit` or `GenerateRandomBit.simulate()` just fine.

**Additional context**
I wasn't sure whether to create this issue in this repo or https://github.com/MicrosoftDocs/quantum-docs/?
cc @KittyYeungQ @geduardo @Bradben @ricardo-espinoza, who are contributors on the the https://docs.microsoft.com/en-us/azure/quantum/how-to-submit-jobs-with-jupyter-notebooks tutorial.

Any help would be appreciated. Thank you!

**Comment by Mobius5150** [comment]
Hi @singular-value - based on the error you're receiving it's likely that the service failed to link your Quantum Workspace to your Storage account and this is blocking submission. This can happen in some cases because of the configuration of your Azure Subscription. Can you please [file a ticket with Azure Support](https://azure.microsoft.com/support/create-ticket/) and they will help you investigate and resolve?

**Comment by singular-value** [comment]
FYI, @ffrachon and team helped me resolve the problem.
For posterity, the "fix" was to wait on the "Create Workspace" interface until the Workspace is fully deployed. Apparently leaving the page during deployment can interfere with the assignment of roles.

Feel free to close this issue.

**Comment by ffrachon** [comment]
Glad we could help!

If you run into this issue:

This issue may happen, during a workspace creation, if Azure Quantum fails to complete the role assignment step when linking the new workspace to the storage account that was specified.
A typical scenario for this situation happens if the tab or web browser window is closed before the workspace creation is completed. You can verify that you are running into this role assignment issue by following these steps:
	
- Navigate to your new quantum workspace in Azure Portal
- Under Overview > Essentials > Storage account, click on the storage account link
- In the left navigation bar, select Access Control (IAM)
- Select Role Assignments
- Verify that your workspace appears as a Contributor
- If the workspace does not appear as a Contributor you can either:
  - Create a new workspace and make sure to wait for the workspace creation to be completed before closing the web browser tab or window.
  - Add the proper role assignment under the storage account
    - Access Control (IAM) > Add role assignments
    - Role > Contributor
    - Assign access to > User, group, or service principal
    - Select > [Workspace name]
    - Save
