### ISSUE TITLE
Qubits not properly released?

### ISSUE THREAD

**Issue by RichardScharf** [microsoft/iqsharp#479]
The phase of released qubits remains and is not affected by measurement, is this intentional?

```
open Microsoft.Quantum.Canon;
open Microsoft.Quantum.Diagnostics;
open Microsoft.Quantum.Core;

operation test () : Unit {
    for i in 1..1 {
        use qubit = Qubit[1];
        Y(qubit[0]);
        DumpMachine();
        ResetAll(qubit);
        DumpMachine();
    }
    DumpMachine();
    use q = Qubit[1];
    DumpMachine();
}
```

Output using
Visual Studio Community 2019 with the Microsoft Quantum Development Kit extension.

Date Installed: 25.06.2021
Version 0.18.2106.148911

```
# wave function for qubits with ids (least to most significant): 0
∣0❭:	 0,000000 +  0,000000 i	 == 	                     [ 0,000000 ]                   
∣1❭:	 0,000000 +  1,000000 i	 == 	******************** [ 1,000000 ]    ↑    [  1,57080 rad ]

# wave function for qubits with ids (least to most significant): 0
∣0❭:	 0,000000 +  1,000000 i	 == 	******************** [ 1,000000 ]    ↑    [  1,57080 rad ]
∣1❭:	 0,000000 +  0,000000 i	 == 	                     [ 0,000000 ]                   

# wave function for qubits with ids (least to most significant): 
∣0❭:	 0,000000 +  1,000000 i	 == 	******************** [ 1,000000 ]    ↑    [  1,57080 rad ]

# wave function for qubits with ids (least to most significant): 0
∣0❭:	 0,000000 +  1,000000 i	 == 	******************** [ 1,000000 ]    ↑    [  1,57080 rad ]
∣1❭:	 0,000000 +  0,000000 i	 == 	                     [ 0,000000 ]
```
Output (picture) using Anaconda3 Jupyter Q# kernel

![Jupyter Output](https://user-images.githubusercontent.com/72913455/125975463-5d610e66-0c03-45a1-b7d5-8d3a60c2dc0d.png)

**Comment by RichardScharf** [comment]
Same problem using Visual Studio Community 2019 with the Microsoft Quantum Development Kit extension.

Date Installed: 25.06.2021
Version 0.18.2106.148911

**Comment by RichardScharf** [comment]
I reproduced this on two different installations as well, my surface book and my desktop PC!

**Comment by RichardScharf** [comment]
The problem does not appear when using a c# Driver program that creates a new instance of a quantum simulator object each time it steps trough the loop.

The problem remains if the loop is inside the using{} Block of the simulator object.

This seems to be analogous to manual rerunning.

**Comment by RichardScharf** [comment]
![Jupyter Output](https://user-images.githubusercontent.com/72913455/125975463-5d610e66-0c03-45a1-b7d5-8d3a60c2dc0d.png)

**Comment by cgranade** [comment]
Thanks for reporting this issue! In this case, I think what is happening is that 𝑌|0⟩ = 𝑖|1⟩, where 𝑖 is an example of a global phase. Since global phases are physically unobservable, the particular global phase that is used to represent the statevector internal to the simulator is not guaranteed. In particular, in the third `DumpMachine` call from your screenshot using a Q# notebook, the state is reported as being 𝑖|0⟩, which is physically the exact same state as |0⟩, since both 𝑖|0⟩ and |0⟩ predict identical measurement probabilities for all possible measurements.

For more information, check out [the "measuring a qubit" section](https://docs.microsoft.com/azure/quantum/concepts-the-qubit#measuring-a-qubit) of our docs, or Chapter 6 of _Learn Quantum Computing with Python and Q#_.

Since this looks to be correct behavior, I'll go on and close this bug for now, but please feel free to re-open if you have additional information. Thank you again for your report!

**Comment by RichardScharf** [comment]
@cgranade Thanks for your quick response!

Is there an operation to reset the phases of all qubits? Even if it's physically impossible, it would be handy to have a "diagnostics operation" for it.

Using VS with a C# driver program I can just create new instances of the simulator automatically each time (especially in loops) thereby resetting the global phase.

In Python I would need to manually retype %simulate wrapperfunc1, wrapperfunc2, ... etc.
to run my Q# program for different inputs.
