### ISSUE TITLE
The test `TestHintOnFailedMagic` fails in VS Test Explorer

### ISSUE THREAD

**Issue by kuzminrobin** [microsoft/iqsharp#543]
In the latest `main` a couple of tests crash in VS Test Explorer (and likely in command line upon "dotnet test"), which results in these 2 tests and all the subsequent tests (totally 65) to stay "Not Run". The CI build does not notice the crash and the not run tests. Bettina says that such crashes typically happen upon `Debug.Assert()` failure (that is why she recommends to avoid using `Debug.Assert()` in C# code).
If we skip the 2 crashing tests and execute the subsequent tests, then we see that the test `TestHintOnFailedMagic` fails.

I'm making a change that removes the crashing code (no need to fix those crashes), but the failing test `TestHintOnFailedMagic` still fails.

**To Reproduce**
```
git clone https://github.com/microsoft/iqsharp.git

cd iqsharp

# (See details in https://github.com/microsoft/iqsharp#building-iq-from-source)
pushd src\Kernel
npm install
popd

# Open `iqsharp.sln` in VS
# <F7>   (Build Solution. Takes a few seconds)
# <Ctrl+e>, <t> or menu Test/"Test Explorer"    (Open the Test Explorer)
# Feel free to expand the tree of the tests - item "Tests.IQsharp"
# <Ctrl+r>, <v>  or Click top left button in Test Explorer toolbar (Run All Tests. Takes couple of minutes)
# Observe that the test "﻿Tests.IQsharp"/"﻿Tests.IQSharp"/﻿IQSharpEngineTests/OpenAliasedNamespaces stays "Not Run", 
  and all the tests after it either (totally 65).
# In the Output window (bottom of the screen) choose in the dropdown menu the item "Tests" and see:
    The active test run was aborted. Reason: Test host process crashed : Process terminated. Assertion Failed
    No Jupyter comms router was provided when this operation was registered. This is an internal error, and should never occur.
# Right-click the test OpenNamespaces (immediately after the crashed OpenAliasedNamespaces) and choose "Run". 
  Observe that it crashes too in the same manner.
# Select all subsequent tests, right-click, and choose "Run". They all succeed except TestHintOnFailedMagic.
```

**Expected behavior**
All tests succeed

**System information**
 - OS: Win

**Comment by cgranade** [comment]
Ah, I found the root cause, and in particular why it doesn't show up in CI, and it's pretty interesting. `TestHintOnFailedMagic` checks that when a user runs an invalid magic command, that the returned error message contains useful hints as to what valid magic commands they may have wanted to run instead. In particular, this test does so by running a particular invalid magic command and checking that the output matches what's expected. When running in "Debug" configuration, the `%attach` magic command is added to the kernel (this magic command is never shipped in release builds, as it only makes sense when IQ# is installed in local development mode), so the output changes to suggest that command.
