### ISSUE TITLE
Passing arguments to operations invoked via %simulate in Jupyter Notebooks

### ISSUE THREAD

**Issue by der-datenzauberer** [microsoft/iqsharp#83]
I get the following error while trying to **pass parameters** to **operations** in Q#. It is quite annoying to **hard-code the parameters** , in order to perform test runs of the operations with different values. 

![image](https://user-images.githubusercontent.com/11174526/72670941-9a203300-3a69-11ea-8f16-698ee0f0ceed.png)

I would like a feature like:
```
function LeftShift(x: Int) : Int {
return x<<<2;
}

%simulate LeftShift argument1
```

**Comment by rmshaffer** [comment]
This has feature has been implemented in commit https://github.com/microsoft/iqsharp/commit/3c4803fee46e069aa59aa509d729524b25d38b57, which is currently in the `feature/azure-client` branch. Will close this issue once the fix is in `master`.

For the example described in the issue above, the syntax for passing an argument will be:
`%simulate LeftShift x=4`
